Gaev hw4
zuevmaxim/CLI pull request #3
Opened 2020-02-25 22:44 UTC by Krock21rus

2020-02-25 22:45 UTC, Krock21rus commented
Максим не удаляй пулл реквест, пожалуйста. Отправил ссылку на него как решение

2020-02-25 22:46 UTC, Krock21rus commented
Travis упал не по моим тестам, вроде

2020-02-25 22:56 UTC, Krock21rus commented
Написать ревью на архитектуру оного одногруппника, указав, что оказалось удобным, а что неудобным при реализации, что можно было бы улучшить:

Архитектуру приложения особо не смотрел, но без документации в ней явно не разобраться.
Решил посмотреть, как запускается встроенная команда, и примерно 10 раз попереходил через разные .run() от разных классов.
Архитектура тестов сильно сковывает, заставляет писать лишний, часто ненужный код, и хотелось бы не использовать его класс для тестирования. Но непонятно, разрешено ли это по архитектуре. Вдруг какой-то фреймворк ищет всех наследников его класса и запускает их и счастье.

Неудобно, что для исполнения команды нужно создать класс, 2 стрима, записать данные, запустить. Хотя бы параметры по умолчанию были бы полезны. Приходится писать вспомогательные функции.

Улучшить? Написать документацию по тестам. Написать документацию для Maintainerов. Упростить(ЗА что вы попросили делать овердизайн :((() иерархию всего. Сделать многопоточным.

2020-03-24 21:55 UTC, Krock21rus commented
Смотреть лучше сюда
https://github.com/zuevmaxim/CLI/pull/4

2020-04-05 14:49 UTC, yurii-litvinov requested changes
При наличии лишних аргументов в cd крешит весь шелл:
```
cd . err
usage: main.py [-h] [path]
main.py: error: unrecognized arguments: err
```
С ls то же самое.

И ещё не нашёл ревью архитектуры, которое просили в условии.

2020-04-05 14:49 UTC, yurii-litvinov commented on commands/CdCommand.py
> +        logging.debug("[LsCommand] path=%s", path)
LsCommand?

2020-04-05 14:49 UTC, yurii-litvinov commented on commands/CdCommand.py
> +                            default=self.environment.get('HOME'))
Винда не выставляет HOME, винда выставляет UserProfile. Главное, что из-за этого оно ругается и команда вообще не исполняется под виндой, даже если ей таки переданы аргументы

2020-04-05 14:49 UTC, yurii-litvinov commented on commands/CdCommand.py
> +            output_stream.write("Something went wrong")
Хочется более подробного error reporting-а: попытка cd в несуществующую папку и/или попытка cd в файл

2020-04-05 17:09 UTC, Krock21rus commented
Писал в сообщении выше:

В задании вроде "Написать ревью на архитектуру оного одногруппника, указав, что оказалось удобным, а что неудобным при реализации, что можно было бы улучшить"
И я написал ревью на те части, которые меня коснулись.

Ревью на всю архитектуру не писал, это правда.
Мне она кажется слишком сложной, есть проблема с работой с потоком ошибок, возможности такой нет. Также не понравились зависимости, которые пришлось ставить. lark и parameterized.
Идея по улучшению мб в том, что можно совместить Command и Handler, ведь Handler это примерно то же самое, что и Command.
Также Handlerы не универсальные. Они принимают и возвращают разные объекты, и выход ParserHandler это list, и вход CommandRunHandler это list. Эта идея позволяет добавлять новые Handlerы и включать их в процесс, но теряются такие связи по параметрам выходным и входным. Мб лучше было бы разделить их как-то дополнительно.

2020-04-05 17:10 UTC, Krock21rus commented
Травис сходит с ума, кажется проблема в нём

2020-05-04 09:40 UTC, yurii-litvinov approved these changes
Да, теперь мне всё нравится, зачтена

2020-06-04 08:10 UTC, merged